import type { Metadata } from "next";
import "./globals.css";
import MiniKitProvider from "@/components/minikit-provider";
import dynamic from "next/dynamic";
import { FrameProvider } from "@/components/farcaster-provider";
import { Toaster } from "@/components/ui/sonner";
import { AudioPlayerProvider } from "@/contexts/AudioPlayerContext";
import localFont from "next/font/local";

const suisseIntlMono = localFont({
  src: "../public/fonts/SuisseIntlMono-Regular-WebS.ttf",
  variable: "--font-suisse-intl-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ErudaProvider = dynamic(
    () => import("../components/Eruda").then((c) => c.ErudaProvider),
    {
      ssr: false,
    }
  );
  return (
    <html lang="en">
      <body className={`${suisseIntlMono.variable} font-mono`}>
        <ErudaProvider>
          <FrameProvider>
            <MiniKitProvider>
              <AudioPlayerProvider>
                {children}
                <Toaster />
              </AudioPlayerProvider>
            </MiniKitProvider>
          </FrameProvider>
        </ErudaProvider>
      </body>
    </html>
  );
}
